<?php
$nigerian_universities = [
    "Abia State University",
    "Achievers University",
    "Adamawa State University",
    "Adekunle Ajasin University",
    "Adeleke University",
    "Ahmadu Bello University",
    "Air Force Institute of Technology",
    "Akwa Ibom State University",
    "Al-Hikmah University",
    "Alex Ekwueme Federal University",
    "Ambrose Alli University",
    "American University of Nigeria",
    "Anambra State University",
    "Anchor University",
    "Augustine University",
    "Babcock University",
    "Bauchi State University",
    "Bayero University Kano",
    "Baze University",
    "Bells University of Technology",
    "Benson Idahosa University",
    "Bingham University",
    "Bowen University",
    "Caleb University",
    "Caritas University",
    "Chrisland University",
    "Christopher University",
    "Clifford University",
    "Coal City University",
    "Covenant University",
    "Crawford University",
    "Crescent University",
    "Cross River University of Technology",
    "Crown Hill University",
    "Delta State University",
    "Dominion University",
    "Eastern Palm University",
    "Ebonyi State University",
    "Edo University",
    "Edwin Clark University",
    "Ekiti State University",
    "Elizade University",
    "Emeka Anyaoku Federal University",
    "Enugu State University of Science and Technology",
    "Federal University Birnin Kebbi",
    "Federal University Dutse",
    "Federal University Dutsin-Ma",
    "Federal University Gashua",
    "Federal University Gusau",
    "Federal University Kashere",
    "Federal University Lafia",
    "Federal University Lokoja",
    "Federal University Ndufu-Alike",
    "Federal University Otuoke",
    "Federal University Oye-Ekiti",
    "Federal University Wukari",
    "Federal University of Agriculture Abeokuta",
    "Federal University of Agriculture Makurdi",
    "Federal University of Petroleum Resources",
    "Federal University of Technology Akure",
    "Federal University of Technology Minna",
    "Federal University of Technology Owerri",
    "Fountain University",
    "Glorious Vision University",
    "Godfrey Okoye University",
    "Gombe State University",
    "Gregory University",
    "Hallmark University",
    "Hezekiah University",
    "Ibrahim Badamasi Babangida University",
    "Igbinedion University",
    "Imo State University",
    "Joseph Ayo Babalola University",
    "Kaduna State University",
    "Kano University of Science and Technology",
    "Kebbi State University",
    "Kings University",
    "Kogi State University",
    "Kwara State University",
    "Lagos State University",
    "Landmark University",
    "Lead City University",
    "Madonna University",
    "Mcpherson University",
    "Michael Okpara University of Agriculture",
    "Modibbo Adama University of Technology",
    "Mountain Top University",
    "Nasarawa State University",
    "Niger Delta University",
    "Nigerian Defence Academy",
    "Nile University of Nigeria",
    "Nnamdi Azikiwe University",
    "Novena University",
    "Obafemi Awolowo University",
    "Obong University",
    "Oduduwa University",
    "Olabisi Onabanjo University",
    "Ondo State University of Science and Technology",
    "Osun State University",
    "Pan-Atlantic University",
    "Paul University",
    "Plateau State University",
    "Precious Cornerstone University",
    "Redeemer's University",
    "Renaissance University",
    "Rhema University",
    "Rivers State University",
    "Samuel Adegboyega University",
    "Sokoto State University",
    "Spiritan University",
    "Southwestern University",
    "Summit University",
    "Tansian University",
    "Taraba State University",
    "The Technical University",
    "Umaru Musa Yaradua University",
    "University of Abuja",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Mkar",
    "University of Nigeria Nsukka",
    "University of Port Harcourt",
    "University of Uyo",
    "Veritas University",
    "Western Delta University",
    "Yobe State University",
    "Yusuf Maitama Sule University",
    "Zamfara State University",
];